language: generic
sudo: required
dist: trusty
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build --build-arg GITHUB_CREDENTIALS_TOKEN=$GITHUB_CREDENTIALS_TOKEN web
script:
- docker-compose run web typesafety --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
env:
  global:
  - secure: AOAo5m+W8IDUUj9Ks9A+CIJ2NgTjI4GtbLPv90xmbB7gAAYc2y0sIZrWE2b6DIFrkaWrU5QU2riGlUre1L6052tG7Xoo2+oyi+pNYsmMLGdKg5c650h1fHNqslB2aI8DZF/HPI5M2POmNUc5ybP4hBLnSJ53KbLvnLt7Ot/UVOAQwn25O01Vu4wuX1NLhMu3CUK390M8o0Oo1nCc/LaKud1EamGwsFc+wA2CE8NOjCOxUwxqIyrCJZE6fLapVciVNlUKTfP23WA3AqyOoAyXqKa/2HGxTiQ9heW1kodv5td3qH2kb/vxzCXni6wc79Yir41of2QjmrB/pGLmTZVuuWksTsQrTuWrtfUjboXzx0CfBWPKzBZI/drdXw/RTdh621zkAAmfc9KbBpCdqyvyF4xxyIt6UrGyD81DZbp6Ma+yKSnRRPC7niztUaDRX4g53vJlNW2+jUSLtwc6StQkbHVH4yq54XvUQJGk/ukocSXZXNcBE5mVIlEfT3IIcP511h7BcZYESLe06opRztQqr8g6SAntxGONjqwbTMZCEygAjEmeQ5eSBttw89D7Sp3Na0wD51zt2LonPHWLH3c45z0Lqo5eTkDuAbd181NAIwjDwd5Z6qSOmGmaDAHvUPwHcHta2a5tzKyKlf8HJppLmf0XR6SDpZ0FjoF4KKRc7/8=
  - secure: QcbUjFqb4UxuvtKBnqEROyVIpdwRWX8ujYvOmLMdepHtfOKKtI03YN2xXjUt8b4wea3nV6uM+A/QIFlEudnIZOWtwTDoHDSoW6aZqKY7zVMjr+HjbEVuYpx7gVszUUYxe7JiZfQagpgcoao3R3GkSRXQU1BC1j0zliWns3s7fkS2ce16azfNvYWMO/+9KR1eo2t1niK+R/Y9Ne/IApzQgBoqdatSvmbjlaJt0q1A7VMizOaPszSvYB//fmCAK5x2st8MBHPgiQjxv6aWkQGSKduRfEEk+X3rfGIl4lKMLVLqLjzb4a2iCZiR3jdOVO7Prnr5pmmiQFj1u8NvgVLoNg/5wYZCd52N92lm5oJ8M69FzNd0tTQvgQ+tRgxL0UVW5iEb5JZ21XKEXga/oesOLUQTyJGwB3C0zHLUnLefA6HwrTCc0D0LIQZNFHzAntcoclN4s3e5ubE1r76GpKKtvwPs0SWXnMZpO/CtN64+GGFmWyaIAGEDXvxHVZRGaVESRY+Wm2pjKZQOTdW7vXEYrQZxluK6xC2amoccyFp0rNbaWNHWRyCTqmHKDSlnGUsHXb5MEI9rsVm1gwFof6SCG2eUn44Lpnsvd/oR8Mi0CX+cwNsoFxGcRvGWrOAcM0R6MPYrUSIVv0mdJEW1Tua9E2SPfOPkXadiUV2OGIun/uU=
  - secure: mks+BNqua8WkDNthftxIr3oiIY6mahGQgbvXAAvo9pdEL0ZytJJGvYB7Aoa8YNFuIbki8W6GZ53xV50t5kKOcFepOAWFXCLoX+91lfV6TrGUL8a3GMsGqwd6QiY+3/0N1CM0e6AKOjwN1C79U+kko/uvvwtL442S0LjuIbw3+g5yZKnca6fcdXMQcDGtKmoonuiSMcysdEgX+GG1qLWe4UtmvlyhyjvjQct2+W/poqRFOepeT5sUaBPynY+GzekCOQAxpqgoUMr4JTYkxlnu8dPKvyO3l9nAZI5bp9+KPjl0zVpEVSRQKNZ4X13k8YwCPFnLMsJU1Gf88xLZLAvAXR/ygsM8/bO+Zdd0kBM8NA562sDrd26JlwhLk5K/bQpRiYA+AzuKZ8AuS/7KZnlqCUv8EtYEfPPR9PMvs7sUBTYOTeXOTly8UJaZrbSHrjW/dXt/3Caj3O+5ofQSmIOW21nlcATmJO3DlyKAEoYltT8j5VhP0xte4xft8rGxgrU0ZJRPa2mZX3T7h7wa8MbT31y735nnzn0Mslco46dfwOoKv4I4Gi39FxjUzIZmrJCbyHzueIgZCjacmjQk+u4wAn9pgIp9tlff1R3NTyPcGD7sO7q3xQKSczbAewNwmwL+Ryp+DEnCmvNoEvTNMGxY/Pe1BS4sDp1753rD9QrHWQ0=
